### ISSUE TITLE
OSX Run Issue: could not load: libiup.dylib

### ISSUE THREAD

**Issue by jdmendoza** [dariolah/nim-iup-examples#2]
I tried to compile & run _example2_1.nim_ using the following command:
`nim compile --run example2_1.nim` 
But it fails with error: `could not load: libiup.dylib`

I just installed nim with `brew install nim` and niup `nimble install niup`, so the packages should all be up to date. Any ideas why this is happening? Let me know if you need any additional info.

**Comment by dariolah** [comment]
Niup requires IUP library installed. They are not distributed with Niup package.

When you run examples they dynamically load IUP libraries (dylib, so, dll).

Please install IUP. That is probably hardest part, it doesn't come as package and I don't see pre-compiled for OSX.
https://webserver2.tecgraf.puc-rio.br/iup/

I assumed that library name would be libiup.dylib. If it's not please let me know what are library names. There are dozen libraries as part of IUP.

**Comment by nodrygo** [comment]
this is just a suggest ;-)
May you could create a installer as this [Common Lisp IUP](https://github.com/lispnik/iup) lib do with this [companion project](https://github.com/lispnik/tecgraf-libs)
wonder if is IUP need also GTK installed on OSX ? 

by the way big congratulations NIUP is an excellent job I like it

**Comment by dariolah** [comment]
Good idea, problem is my free time and priorities. For next version of IUP they plan to have packaging for RPM and DEB distributions. We'll see how things develop with time. If IUP team doesn't deliver packaging..

For OSX, until they provide official native driver your options are X11(GTK) or 3rd party support like IupCocoa. Haven't tested it. And official native driver for MacOS X is in section 'Future Versions (??)' :/

https://github.com/ewmailing/IupCocoa
