### ISSUE TITLE
Could you please sync all examples with the latest version of niup? 

### ISSUE THREAD

**Issue by pikhovkin** [dariolah/nim-iup-examples#3]
Could you please sync all examples with the latest release version of niup?

**Comment by dariolah** [comment]
Examples in niupc/, using C-like API are in sync.
Examples in niup/, Nim friendly API is in sync with HEAD of master branch.

Use `nimble install niup@#head`

This is still work in progress, hope soon to have that API completed. Then regular nimble install will work with examples.
