### ISSUE TITLE
Error on niupc examples 

### ISSUE THREAD

**Issue by nixfreak** [dariolah/nim-iup-examples#4]
I'm probably wrong about this I get errors compiling the majority of the niupc examples. 
Example "tree.nim"  https://github.com/dariolah/nim-iup-examples/blob/master/niupc/tree.nim the code states. 

`import niup`
`import niupext`
Shouldn't it be 

`import niup/niupc`
`import niup/niupext`

Same with the webbrowser.nim example 

`import niup`
`import niupext`
Shouldn't it be 

`import niup/niupc`
`import niup/niupext`

If this is correct I could do  pull request to help out , I really like this project. Thanks again.

**Comment by dariolah** [comment]
You are right, it should be 'niup/niupc'.
If you can do pull request that would great.

**Comment by dariolah** [comment]
Thank you for PR
